# Recovered configuration - Thu Jun 12 00:19:45 EDT 2025
export BUCKET_NAME="devops-bootcamp-1749585074"
export DISTRIBUTION_ID="E3FB9TJY2P04OK"
export CLOUDFRONT_URL="https://d1t1et5tjvep2.cloudfront.net"
export USER_POOL_ID="us-east-1_sgcR0nyyj"
export PUBLIC_CLIENT_ID="6qgl1afuotr6u1pa4n2kfnrcml"
export API_ID="hdxbz1zbx4"
export API_ENDPOINT="https://hdxbz1zbx4.execute-api.us-east-1.amazonaws.com/prod"
export LAMBDA_FUNCTION_NAME="devops-bootcamp-api"
export USERS_TABLE="devops-bootcamp-users"
export CHALLENGES_TABLE="devops-bootcamp-challenges"
export PROGRESS_TABLE="devops-bootcamp-progress"
export SESSIONS_TABLE="devops-bootcamp-sessions"
export REGION="us-east-1"
