export BUCKET_NAME=devops-bootcamp-1749585074
export WEBSITE_URL=http://devops-bootcamp-1749585074.s3-website-us-east-1.amazonaws.com
export REGION=us-east-1
export DISTRIBUTION_ID=E3FB9TJY2P04OK
export CLOUDFRONT_DOMAIN=d1t1et5tjvep2.cloudfront.net
export CLOUDFRONT_URL=https://d1t1et5tjvep2.cloudfront.net
export USER_POOL_ID=us-east-1_sgcR0nyyj
export CLIENT_ID=1ldgvhnkgp4qbpmj7b27a235oe
export CLIENT_SECRET=1hp7lff8l31ppgbb5r3hb0ar0ahhs55artr6dje6dqssdgtvrsro
export COGNITO_DOMAIN=https://cognito-idp.us-east-1.amazonaws.com
export REGION=us-east-1
export API_GATEWAY="devops-bootcamp-api"
export AUTH_TEST_URL=https://d1t1et5tjvep2.cloudfront.net/auth-test.html
export LAMBDA_ROLE_ARN=arn:aws:iam::677381153775:role/devops-bootcamp-lambda-role
export LAMBDA_ROLE_NAME="devops-bootcamp-lambda-role"
export LAMBDA_ROLE_ARN=arn:aws:iam::677381153775:role/devops-bootcamp-lambda-role
export LAMBDA_ARN=arn:aws:lambda:us-east-1:677381153775:function:devops-bootcamp-api
export LAMBDA_FUNCTION_NAME=devops-bootcamp-api
export LAMBDA_URL=https://ucj5xcgpf5vdilzy336ocazp7y0vvtya.lambda-url.us-east-1.on.aws/
export API_ID=hdxbz1zbx4
export ROOT_ID=r7vdz4fcn5
export API_ENDPOINT=https://hdxbz1zbx4.execute-api.us-east-1.amazonaws.com/prod
export DASHBOARD_URL=https://d1t1et5tjvep2.cloudfront.net/dashboard.html
export API_STATUS="Production Ready"
export PUBLIC_CLIENT_ID=6qgl1afuotr6u1pa4n2kfnrcml
export USERS_TABLE=devops-bootcamp-users
export CHALLENGES_TABLE=devops-bootcamp-challenges
export PROGRESS_TABLE=devops-bootcamp-progress
export SESSIONS_TABLE=devops-bootcamp-sessions
export DYNAMODB_STATUS="Production Ready"
export ECR_REPO_URI=677381153775.dkr.ecr.us-east-1.amazonaws.com/devops-bootcamp/challenges
export CLUSTER_NAME="devops-bootcamp-challenges"
export EXECUTION_ROLE_ARN="arn:aws:iam::677381153775:role/devops-bootcamp-task-execution-role"
export CONTAINER_LAMBDA_ARN="arn:aws:lambda:us-east-1:677381153775:function:devops-bootcamp-containers"
export API_ID=$(aws apigateway get-rest-apis --query "items[?name=='devops-bootcamp-api'].id" --output text)
export API_RESOURCE_ID=$(aws apigateway get-resources --rest-api-id $API_ID --query "items[?path=='/api'].id" --output text)
export REGION="us-east-1"
export API_STAGE="prod"
export LAMBDA_FUNCTION_ARN=$(aws lambda get-function --function-name devops-bootcamp-containers --query "Configuration.FunctionArn" --output text)
export ECR_REPO_NAME="devops-bootcamp/challenges"
export CONTAINERS_ID=7ir2nu
export CLUSTER_NAME=devops-bootcamp-challenges
export ECR_REPO_URI=677381153775.dkr.ecr.us-east-1.amazonaws.com/devops-bootcamp/challenges
export SECURITY_GROUP_ID=sg-07b2c1196fb935bd7
export CONTAINER_LAMBDA_ARN=arn:aws:lambda:us-east-1:677381153775:function:devops-bootcamp-containers
export CONTAINER_SYSTEM="Production Ready"
